# application-postgres.yml
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/firstdb
    username: postgres
    password: 1567
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway
  flyway:
    enabled: false
    locations: classpath:db/migration